### ISSUE TITLE
Color scheme conflict

### ISSUE THREAD

**Issue by winduptoy** [regolith-linux/regolith-st#1]
The color scheme of the terminal makes it impossible to see certain text. For example, using neovim I'm editing a `.vimrc` file and some text colors match the background.

![Screenshot from 2019-05-02 22-35-43](https://user-images.githubusercontent.com/270504/57117550-e3d5bb80-6d2a-11e9-9d86-9cf19832dea6.png)

Here is the same file after I've dragged the mouse across it to select all the text, revealing text that had the same color as the background.

![Screenshot from 2019-05-02 22-36-34](https://user-images.githubusercontent.com/270504/57117573-1da6c200-6d2b-11e9-8698-c183e98c75f2.png)

Notice lines 3, 4, and 8-14.

What would be the best course of action to correct this? Is this an issue with the st color theme, or perhaps and issue with the neovim syntax highlighting theme?

**Comment by kgilmer** [comment]
Does the same issue occur in light mode? (Toggle w F6)

**Comment by kgilmer** [comment]
To answer your question, I have not seen this issue myself.  I use vim, but do not have any customization.  This is where the solarized colors are defined for st: https://github.com/regolith-linux/regolith-st/blob/master/debian/patches/st-solarized-both-20190128-3be4cf1.diff

I am guessing that your vimrc uses similar colors and there is some text color that is too close to the background color of st...

**Comment by winduptoy** [comment]
Yep.

![Screenshot from 2019-05-02 23-32-13](https://user-images.githubusercontent.com/270504/57118627-8a718a80-6d32-11e9-8a97-af6bafda14fc.png)

![Screenshot from 2019-05-02 23-31-34](https://user-images.githubusercontent.com/270504/57118614-7a59ab00-6d32-11e9-812b-53b642668ee2.png)

**Comment by winduptoy** [comment]
To clarify, this is all happening with a vanilla install of everything.

**Comment by kgilmer** [comment]
Oh I see.  I just installed neovim and see the same thing you do.  Then I compiled st without any customization and my bashrc looks fine in neovim, so it's def something with the patches applied to st.  I played around with the TERM variable but no luck.  I suggest for now either using regular vim (2:8.0.1453-1ubuntu1) (install w/ `sudo apt install vim`) or perhaps use another terminal with neovim.

**Comment by kgilmer** [comment]
After some more searching I found that the Solarized patch that is in regolith-st recommends changing the colors for vim (I'm guessing neovim?): 

https://st.suckless.org/patches/solarized/
https://bbs.archlinux.org/viewtopic.php?id=164108

Would love to know if this fixes your issue w/ neovim!

**Comment by winduptoy** [comment]
Installing this solarized theme did the trick! Maybe mentioning this issue in some documentation would help someone in the future.

https://github.com/altercation/solarized/tree/master/vim-colors-solarized

**Comment by kgilmer** [comment]
Great to hear and thanks for following up @winduptoy .  I've added a README and referenced this issue: https://github.com/regolith-linux/regolith-st/tree/master

**Comment by kgilmer** [comment]
Hi there!
 
 Find your next opportunity at an event of your interest
 
 
 
 
 
 10times is the world's largest business event platform to find events,
business conferences, trade shows, global seminars, networking meets and
workshops.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Events near me
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Connect with 40m+ event goers world wide.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 300k business events from around the globe.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Professionals from more than 100 industries.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Network with event-goers from more than 200 countries & 8000 cities.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 For any queries, reach out to Helpdesk
 
 
 
 
 
 
 Download our official Apps
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 | Manage Email Subscription

Unsubscribe From This List http://links.10times.com/asm/unsubscribe/?user_id=1002061&data=NMsSPo3Ui9USh6Tso_gtR2AkeYk-6KYZIpyuSDpMFqEwbxT-19bG0tsUzIzUffhbcnAWzIqhm5gq2NJ-eTMmzTW-4uXXgVUCT6OlHQxV68_7CdKK28z4I8vp96rGd7_MlYYgqKuOXY9wA_x1Q7E-rGX54gQmCVsSCvEAJXP1fwJPMdF7XlPvAcdp6-LxJDbEDOeMKJ7XYz-ThSR-KPHhM1ptmznBdKHCpzT0zUhprFamTMh13luWpgrXnygQ3b7B0Yx4AeKY9MmPHarU_IN2VTPkhJG8x7nXy4I7xPwRYZZIODUNMaq-D8vzFXkLhef4ns0YffZLd4juNxcCeUAf-M_rrXO-gdqkmz1gLoeE0w5lOFrmeMjD7N2rF3OI1rIH0msbiyFP5cda1opQLpqufv94S36JAZh1umQonBdf2zDcjW8P346KyQc2XkHXjJrbsi7tnH89PS4D6BP2D6nWZ-zR2JSf_tqhZlg1urCy8T6x0e1WiI0E3x5YLGY--tJtt0BxxY-SP9ICZt_NvV4Yar-PO2v9tJLgEgI-ZirbdVM= | Manage Email Preferences http://links.10times.com/asm/?user_id=1002061&data=FDpNfbC1S5qSny9DpOwNo1jYYVQkr5JMAa-DMJbe_-ByQdJJ4koHKb7XlR1K1IN5iAyl2vYDxvPdr9hTXYuvj_H13eK7EZN0_cwTWS4SPUqH_i8Ie3BLGFnkgqRmmfzFnnbg96yysdUmSfytjNtDvnMbIwfMzXvGIDfmVHTultTipbDco3sD-uIA-d16xg0X8l5WW9YCevFelB4IhUmf-7xMSy-Sgy88Bc-JlenchEPXCV5DYQqo9n2o8Nbaj0NoLTWvlD3HxgvKnM92Z2fHnvdOPdr_Q0YrxLLQPW7RvzwiRQRegb3ZPf3qjyeivpq-0DyBju76fJvFwFZPHA-GeKq4qBwmxxFbvLL3f9GMkaq7kcS9PNCmYFyAeAZrtQXkjQkoeKvwaVz_UgPvoUFfcpRdyhQ6VDFjknPYgGgVQTfTq7wAjfGktIsFj6S7Au2UkF0yqPvMXxdwTcglfqTa5SXMiHlZ2SXSol3YN4MR6BzYuGmpkGgBolQZS_rM1ocLSutkpbmbsrEHTUxukIDGZ9Zqu_DnPTjnHrVonq9X3cY=

**Comment by winduptoy** [comment]
@kgilmer I think you've been hacked dude ☝️

**Comment by kgilmer** [comment]
Thanks @winduptoy , yep seems so.  Hopefully changing all my passwords is enough. :worried:
