### ISSUE TITLE
Remove regolith-st will remove regolith-desktop

### ISSUE THREAD

**Issue by shijiantian** [regolith-linux/regolith-st#10]
I prefer to use gnome-terminal , so I try to remove regolith-st. But, the apt show me that if I try to remove regolith-st ,regolith-desktop will be removed too.
Perhaps this is not a bug,but  it looks odd.

**Comment by kgilmer** [comment]
Yes it's a package dependency, and Regolith's default configuration will break without it.  It's a small program (~40Kb) so it shouldn't matter for storage concerns.  You can change the default terminal to something else and not even realize it's there.  See https://regolith-linux.org/howto.html#default-term for details.
