### ISSUE TITLE
Add Clipboard to regolith-st

### ISSUE THREAD

**Issue by kejoff** [regolith-linux/regolith-st#11]
Hi,

I know we need to patch it but there is nowhere I can find /regolith-st/patches so I can patch it easily.
I guess I won't be the only one to ask when you are going to add clipboard to regolith-st. It's the only thing which bother me with regolith.

Thanks,
Kévin.

**Comment by kgilmer** [comment]
Hi Kévin :smile: , here is the patches directory for `st`: https://github.com/regolith-linux/regolith-st/tree/debian/debian/patches.  The README of the project explains the Debian packaging build tools that apply them before building the program.

Out of curiosity, what workflow does a clipboard patch enable that isn't present?  At times I use the mouse to select text and ctrl-shift-[c|v] to copy paste.  Is there an easier way?

**Comment by kejoff** [comment]
Hi kgilmer,

My bad to bother you I tried a lot of combinations but not this one x).
Last question, is there any file I could modify to take ctrl+alt+[c|v] ?

Thanks a lot for your quick answer

**Comment by kgilmer** [comment]
Good question @kejoff !  I have not found a way of doing that, but it must be possible.  Coming from a mac (a few years back now) I wanted to patch St to not require the shift as well.  My code changes seemed to have no effect so it's more complicated than modifying [this value](https://git.suckless.org/st/file/config.def.h.html#l184).  If you figure out, let me know!

**Comment by kgilmer** [comment]
Closing as original issue resolved.
