### ISSUE TITLE
More Color Issues

### ISSUE THREAD

**Issue by SoarinFerret** [regolith-linux/regolith-st#12]
I have seen #1 , but this seems to effect more than just neovim - htop and powershell core are also affected. I technically have a fix for PowerShell Core, but I didn't know if this means I'm going to run into more applications with this issue or not.

## htop

Easiest way to show this is with htop. The following screenshot shows Gnome Terminal on top of st: 

![image](https://user-images.githubusercontent.com/33401067/72775036-74626d80-3bd2-11ea-952a-9c789542d6a5.png)

Notice how in gnome terminal you can see percentages, and the root user is visible for PID 2282. In st, those are not visible.

## PowerShell Core

Here is an example with PowerShell Core. I ran the command "Get-Uptime -Since", however, you can't see the "-Since" parameter. I then update PSReadline to use gray as the color for parameters, and you can see the "-Since" parameter:

![image](https://user-images.githubusercontent.com/33401067/72775885-b6d97980-3bd5-11ea-95c4-ec96e3df65c9.png)

The PowerShell issue is not as big of a deal, mainly because I can add the PSReadline update to my profile. 

However I'm not sure if this issue is going to become more obvious with other applications - it seems that specific color is not showing up on st and multiple applications appear to be using it.

**Comment by kgilmer** [comment]
HI @SoarinFerret , thank you for the detailed report.  I've been heads down on a big release and have not had time to look into this.  In the short term, you may have a better experience with another terminal app.  You can see here for details of how to update Regolith for a different one: https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Change-the-default-terminal-from-st-to-gnome-terminal

**Comment by SoarinFerret** [comment]
This has been fixed by updating to the latest release of Regolith - thanks!
