### ISSUE TITLE
Ignores the desktop scaling setting from Control Center.

### ISSUE THREAD

**Issue by jessegranger** [regolith-linux/regolith-st#13]
Makes st not usable on a high DPI screen.

Super+c to open Control Center, navigate to Devices -> Displays.

Set the "Scale" option to anything except 100%, hit Apply.

Observe that st does not change the rendered font size.

Typical key shortcuts like Ctrl-+, Ctrl-Shift-+, also do not change the font size.

**Comment by kgilmer** [comment]
Thanks for the bug report @jessegranger .  Currently there is no integration between gnome and st.  I'll look into it.

**Comment by kgilmer** [comment]
To change the scale in X (not GNOME) apps, use the Xft.dpi setting.  Described here: https://regolith-linux.org/docs/howto/override-xres/#example---update-the-ui-for-high-dpi-screens
