### ISSUE TITLE
Add "alpha" patch to regolith-st

### ISSUE THREAD

**Issue by HikloLime** [regolith-linux/regolith-st#3]
t would be super nice if you could add the alpha patch to regolith-st as I love transparent terminal emulators. This could also potentially be altered through the .Xresources file by adding alpha hex values to the color codes.

The patch I'm referring to is this one:
https://st.suckless.org/patches/alpha/

**Comment by kgilmer** [comment]
This is pretty late but a user found that the `transset` program will allow the opacity to be dynamically changed per window.  This works in `st` so I believe it's just a matter of configuring the background color transparancy as desired.

```
$ /usr/bin/transset -pt 0.75
```
