### ISSUE TITLE
ZSH-autosuggestions does not work in St

### ISSUE THREAD

**Issue by waltsims** [regolith-linux/regolith-st#5]
### Describe the bug
ZSH only autosuggests one character when used with st terminal emulator.

### To Reproduce
In St terminal emulator with the default config from regolith-linux, the autocomplete only works for the character under the cursor. With the gnome-terminal on the same machine the plugin works.

### Expected behavior
I expect the behaviour between st and gnome-terminal to be the same.

### Screenshots
![Screenshot from 2019-08-28 10-03-46](https://user-images.githubusercontent.com/8669206/63837180-4490a000-c97b-11e9-9257-86ccfc0a5fd7.png)

### Desktop
 - VERSION="19.04 (Disco Dingo)" Regolith-Linux-Desktop
 - zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
 - commit 43f3bc4010b2c697d2252fdd8b36a577ea125881

### Note
moved from https://github.com/zsh-users/zsh-autosuggestions/issues/469

**Comment by kgilmer** [comment]
Hi @waltsims , I am unable to reproduce this.  I installed `zsh`, and then started a new st terminal w/ the zsh shell: `$ /usr/bin/st /usr/bin/zsh`.  I went through the configuration wizards and basically accepted the defaults.  When I tab complete directories I am able to see the entire line.

However, I notice I'm not seeing colors as I would in bash.  Any idea what the difference between your configuration and mine is?

**Comment by waltsims** [comment]
I can also tab complete directories but the shadowed text does not show up. This can be seen in the right and side of image). Maybe auto-complete was the wrong wording. 

Tabbed auto-complete works. The auto-suggestions (see right hand side of image above) does not.

**Comment by kgilmer** [comment]
Hmm, how do I enable autosuggestions in zsh?  
```
$ zsh --version
zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
```

**Comment by waltsims** [comment]
it's a package. There are [a few installation methods](
https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md). I used the oh-my-zsh method.

I think this is an issue with colors as experienced with https://github.com/regolith-linux/regolith-st/issues/1. I'm seeing similar symptoms.

**Comment by waltsims** [comment]
This is soved with https://github.com/zsh-users/zsh-autosuggestions/issues/469.

I set the value to:

```
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=6"
```
