### ISSUE TITLE
st crashes when listing directories w/ font glyphs not available in configured font

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-st#6]
St will exit in the following code block when trying to list directory contents with glyphs not present in the configured font:
```
                        if (!frc[frclen].font)
                                die("XftFontOpenPattern failed seeking fallback font: %s\n",
                                        strerror(errno));
```

**Comment by kgilmer** [comment]
I can only reproduce this on one computer.  I have made the installed font list identical between a working and non-working computer, and so have removed a font installation issue from being able to resolve the problem.

As this issue at present has an unknown root-cause, I'm unsure of a fix at this point.

**Comment by jc00ke** [comment]
I'm seeing this now too.
![Screenshot from 2019-09-16 05-39-43](https://user-images.githubusercontent.com/18191/64958753-a8084200-d844-11e9-82cd-80eb3d7170b6.png)

**Comment by jc00ke** [comment]
I'm pretty sure this is crashing when emoji are not present. I first experienced this when running `npm install` and again when `ls ~/Downloads` where I have a file called 
![image](https://user-images.githubusercontent.com/18191/64960357-fbc85a80-d847-11e9-8b6d-0f0daccca16e.png) where that file is possibly the most awesome tweet reply ever:

![Screenshot_2019-05-16 MC HAMMER on Twitter jc00ke 👊 ](https://user-images.githubusercontent.com/18191/64960520-4518aa00-d848-11e9-9442-6d9988c33872.png)

**Comment by kgilmer** [comment]
Ok, now that someone other than me is seeing this I'll spend more time on it.  I want to try a simple fix which is to not destroy the universe in the case that a font cannot be rendered.  There is probably a more elegant fix, but this is what I have at the moment.  Will keep you posted @jc00ke .

**Comment by kgilmer** [comment]
Modifying x.c to simply skip characters it cannot find glyphs for seems to prevent the crash, although it does not print anything at all for offending characters so probably not the best fix.  Will keep looking into this.

**Comment by kgilmer** [comment]
There is a related issue mentioned in the ST FAQ: http://git.suckless.org/st/file/FAQ.html line 168.

**Comment by kgilmer** [comment]
Installing the noto color font fixed the issue for me.  @jc00ke can you give this a shot?
```
sudo apt install fonts-noto-color-emoji
```

**Comment by jc00ke** [comment]
![image](https://user-images.githubusercontent.com/18191/65060663-293b0400-d92d-11e9-9e0a-17f8a6ba8932.png)

**Comment by kgilmer** [comment]
haha, awesome ok I'll add `fonts-noto-color-emoji` as a dependency of `regolith-st`.
