### ISSUE TITLE
Font size is pretty small on a 4K display

### ISSUE THREAD

**Issue by abdollahpour** [regolith-linux/regolith-st#7]
I have a 4K display. The other apps are scale correctly but the default font on Regolith terminal is pretty small.

**Comment by kgilmer** [comment]
Hi @abdollahpour :smile: .  You can update the font for the terminal [here](https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/typeface-sourcecodepro#L5).  To create your own config files, have a look at [this page](https://regolith-linux.org/configuring.html).

**Comment by abdollahpour** [comment]
The problem solved after the first update. Now it's ok using the default config. Thanks

**Comment by kgilmer** [comment]
:+1:

**Comment by raymestalez** [comment]
Hey guys! I've just installed regolith for the first time, most of the stuff works great, but this is one problem i can't seem to solve. Links in @kgilmer 's post are broken.

Can you please help me to figure out how to increase the font size? On my high-dpi display it's tiny, but only in terminal, all the other apps and everything looks great. (I'm running PopOS, and it applies it's own styling to a lot of stuff, I think. But regolith terminal for some reason is not affected).

**Comment by kgilmer** [comment]
Hi @raymestalez , sorry about the broken link.  The page moved here: https://github.com/regolith-linux/regolith-desktop/wiki/Customize

In essence you just need to update an Xresource value `St.font`.  The page linked will describe how to copy the default Xresource and make the change.

One thing to keep in mind is that Regolith 1.3 was *just* released (5 minutes ago) and the styling work has gotten a bit simpler.  So, it may be worth updating first, and then you can refer to the new documentation for changing the font: https://regolith-linux.org/docs/customize/styles/

**Comment by Zackhardtoname** [comment]
Hi, I just installed it on Ubuntu 18.04 through the PPA but still can't change the font for the bottom bar or terminal. 
To `~/.Xresources-regolith` I added 
`St.font: Source Code Pro:pixelsize=60:antialias=true:autohint=true`
![image](https://user-images.githubusercontent.com/25935197/77844330-eb3c5980-7173-11ea-89c3-055c1f42f622.png)

**Comment by kgilmer** [comment]
Regolith provides two complementary Xresource customization options:

`~/Xresources-regolith` overrides *all* Xresource values defined in Regolith with whatever is in this file.
`~/.config/regolith/Xresources` overrides specific values that are added, after the defaults are loaded by Regolith.

Here is the documentation for Regolith Xresource keys: https://regolith-linux.org/docs/reference/xresources/

I believe you want to use option two instead of the first.  Here is a sample of how I updated all font sizes in Regolith:

```bash
$ echo "St.font: Source Code Pro:pixelsize=20:antialias=true:autohint=true" >> ~/.config/regolith/Xresources
$ echo "i3-wm.bar.font: pango:Source Code Pro Medium 20, Material Design Icons 20"  >> ~/.config/regolith/Xresources
$ echo "i3-wm.font:     pango:Source Code Pro Medium 20"  >> ~/.config/regolith/Xresources
$ echo "i3xrocks.value.font:    Source Code Pro Medium 20" >>  >> ~/.config/regolith/Xresources
$ echo "rofi.font:      Source Code Pro Medium 20" >> ~/.config/regolith/Xresources
$ regolith-look refresh
```

![image](https://user-images.githubusercontent.com/49683/77856348-5d7c6080-71ab-11ea-8861-e939beeff338.png)
